formatter: "markdown" # this is required

version: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: ["resources", "data-sources", "modules"]
  show: []

output:
  file: "README.md"
  mode: inject

content: |-

  # Terraform DigitalOcean Droplet Module

  The Terraform DigitalOcean Droplet Module is designed to automate the creation of DigitalOcean droplets
  with opinionated and standardized configurations for different deployment scenarios.
  The primary objective of this module is to promote the DRY (Don't Repeat Yourself) principle,
  reducing code duplication through the use of abstractions and avoiding unnecessary redundancies.

  ## Usage

    ```hcl
    {{ include "examples/simple-droplet/main.tf" }}
  ```

  ### Examples

  The following examples are available:

  - [Simple Droplet](./examples/simple-droplet)
  - [Droplet with Volume](./examples/droplet-with-volume)
  - [Droplet with Load Balancer](./examples/droplet-with-loadbalancer)
  - [Droplet with Firewall Rules](./examples/droplet-with-firewall-rules)

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: false
