formatter: "markdown" # this is required

version: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: ["resources", "data-sources", "modules"]
  show: []

header-from: main.tf

output:
  file: "README.md"
  mode: inject

content: |-

  # Terraform module example

  This Terraform [Resource Module](https://www.terraform-best-practices.com/key-concepts#resource-module) creates a an opionated digitalocean droplet
  with commonly used options in osmosis deployments.

  ## Usage

  Some examples can be found in this repository:

  - [Use case 1](./examples/use-case-1)

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}  

  {{ .Outputs }}

  ## Usage

  ```hcl
  {{ include "examples/use-case-1/main.tf" }}
  ```

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: false
